canonical/microcluster

example/cmd/microctl/main.go
example/cmd/microctl/shutdown.go
internal/daemon/daemon.go
internal/db/db.go
internal/db/dqlite.go
internal/endpoints/network.go
internal/endpoints/socket.go
internal/rest/client/client.go
internal/rest/client/shutdown.go
internal/rest/resources/cluster.go
internal/rest/resources/heartbeat.go
internal/rest/resources/resources.go
internal/rest/resources/shutdown.go
internal/state/state.go
internal/sys/environment.go
microcluster/app.go

Depends on #4 
This adds several bug fixes that I noticed upon more nuanced testing:
* Most importantly, this moves initiating the heartbeat out of the dqlite dialFunc. Calls to the dqlite client methods (to check the leader and cluster status during a heartbeat) will initiate further calls to the dialFunc, which calls more heartbeats, and on and on. I noticed my CPU spiking up to 600% from getting slammed with heartbeat requests. The corresponding commit here adds a helper that calls the heartbeat function every second, and is now set up to run in a goroutine upon opening the database.
* Auto-schema-update logic was missing from the heartbeat sequence. Now there is an environment variable: `SCHEMA_UPDATE` that will be checked for an auto-update executable.
* Adds a 5s context timeout for …

Various fixes.

---

cluster/token_records.go
cluster/token_records.mapper.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/resources/tokens.go
internal/rest/types/cluster.go
internal/rest/types/tokens.go

This changes tokens to store the cluster certificate fingerprint rather than the whole certificate.  The certificate is then checked against the actual cluster using `GetRemoteCertificate` and a cluster member address from the token.
Additionally, all references to the internal token key have been renamed to `secret`.

Token changes

---

example/README.md
example/cmd/microctl/cluster_members.go
internal/rest/client/cluster.go
internal/rest/resources/cluster.go
internal/rest/resources/resources.go

Adds the ability to remove a cluster member via `DELETE` to `/cluster/NAME` on both the control and public endpoints.
When a cluster member is removed, its state directory is wiped via a `PUT` to`/cluster/NAME` that is initiated by the `DELETE`. Its database is stopped and its daemon is then reset, so it can be re-initialized with an `init --bootstrap` or `init --token`. 
The CLI example has also been slightly edited:
`microctl cluster list` now prints the cluster information.
`microctl cluster remove` removes a cluster member.

Remove a cluster member

---

client/client.go
example/api/endpoints.go
example/api/extended.go
example/client/client.go

Noticed a bug with the `Query` helper, which was making requests for extended APIs on the internal public API of microcluster. 
Extended apis are now correctly all going through `/1.0`.
Public internal APIs are `/cluster/1.0`
Restricted internal APIs `/cluster/internal`
and Control socket APIs are `/cluster/control`

Endpoint fix

---

example/cmd/microd/main.go
internal/daemon/daemon.go
internal/rest/resources/control.go
internal/state/state.go
microcluster/app.go

Adds an init hook that can be passed to the daemon via `microcluster.Start`, which is run on a call to `microcluster.NewCluster()` (bootstrap) or `microcluster.JoinCluster()` (join)
The hook is of form `func(state *state.State, bootstrap bool) error`

Init hook on bootstrap/join

---

internal/rest/resources/heartbeat.go

I wasn't able to replicate the panic, but it seems to be coming from the `sql.DB` type, so this adds a check to ensure the database is actually open before attempting to respond to a heartbeat.
I'm starting a cluster like this, and did not run into this issue.
https://paste.ubuntu.com/p/fs5nDGs2rs/

Ensure database is open before heartbeat response

---

cluster/cluster_members.go
cluster/cluster_members.mapper.go
cluster/token_records.go
cluster/token_records.mapper.go
example/database/extended.mapper.go
example/database/extended_table.go

This correctly applies the `primary=yes` lxd-generate tag to the `InternalClusterMembers` struct on the `Name` field, which corresponds to the unique `name` column on the `internal_cluster_members` table.
Additionally, this updates the `--database` (or `-d` shorthand) flag to expect the full import path for the cluster package, rather than just the package name and hoping `goimports` finds the right one.

Fix internal_cluster_members primary key for lxd-generate and update invocations.

---

example/cmd/microctl/main_init.go
internal/rest/client/control.go
microcluster/app.go

Allows passing a `time.Duration` to `microcluster.NewCluster` or `microcluster.JoinCluster` to deal with particularly long post-initialization hooks. If the time passed is 0, the default `microcluster.Microcluster` context will be used in the request.

microcluster/app: Add customizable timeout to bootstrap/join

---

example/README.md
example/api/extended.go
example/cmd/microctl/main_init.go
example/cmd/microd/main.go
internal/daemon/daemon.go
internal/db/dqlite.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/resources/heartbeat.go
internal/rest/rest.go
internal/rest/types/control.go
internal/state/state.go
internal/trust/remotes.go
microcluster/app.go

Previously, the daemon would require a listen address to be supplied in order to start, and the value would not be stored anywhere. A restart would require specifying this address again.
Additionally, the cluster member name for each daemon was generated by its state directory name (for testing, mainly). This was problematic for scripting as each daemon would need a unique state directory name.
To solve both of these problems, this updates the MicroCluster daemon to accept a `name` and `address` argument upon bootstrapping or joining a cluster with a token. These values will then be saved in a `daemon.yaml` file in the state directory. 
* Updates go mod and lxd-generate code to the most recent updates.
* Supplies a context to helpers from LXD that now require it.
* As we want to update …

Supply daemon address/name on bootstrap/join

---

config/hooks.go
example/cmd/microd/main.go
internal/daemon/daemon.go
internal/daemon/hooks.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/resources/heartbeat.go
internal/state/state.go
microcluster/app.go

Adds a `Hooks` interface under a `config` package. There are 5 hooks currently defined:
* `OnBootstrapHook` which runs after a bootstrap
* `OnStartHook` which runs after the daemon starts, and before `waitready` returns
* `OnJoinHook` which runs after joining an existing cluster
* `OnRemoveHook` which runs on the leader after a cluster member is removed
* `OnHeartbeatHook` which runs on the leader after a successful heartbeat
These can be implemented and the parent struct can be supplied to `microcluster.Start`.
The `State` has two additional functions for `OnRemoveHook` and `OnHeartbeatHook` as these are actions that take place over the API. Alternatively I can stick them in the endpoint handler and have them run after the specific endpoints are hit. This would avoid having to add the …

Hooks interface

---

example/cmd/microctl/cluster_members.go
example/cmd/microctl/extended_cmd.go
internal/daemon/daemon.go
internal/rest/client/cluster.go
internal/rest/client/heartbeat.go
internal/rest/client/ready.go
internal/rest/client/sql.go
internal/rest/client/tokens.go
internal/rest/resources/control.go
internal/rest/resources/database.go
internal/rest/resources/heartbeat.go
internal/rest/resources/ready.go
internal/rest/resources/resources.go
internal/rest/resources/shutdown.go
internal/rest/rest.go
microcluster/app.go
rest/rest.go

* Internally:
* Exposes every API endpoint on the unix socket. There are 2 endpoint paths exclusive to the unix socket for bootstrapping and shutting down the daemon. 
* Publicly:
* Each `rest.Endpoint` has a `AllowedBeforeInit` flag, that if set to `true`, will allow the endpoint to go through before the database is initialized. 
* `microcluster.Client` has been replaced with `microcluster.RemoteClient` in case we want to talk to some other microcluster daemon.

Use the unix socket for all endpoints

---

client/client.go
internal/rest/client/client.go
internal/rest/rest.go
rest/rest.go

Closes #31 
Adds a `ProxyTarget` flag to each request method handler. If this is true, and the request URL has `?target=name` set, we will attempt to send the request over to the cluster member with the given `name`. 
A client method `UseTarget` has been added, which will return a new `client` with the `?target=name` query set.

Forward request to target if `?target=name` is specified

---

internal/rest/resources/cluster.go

After we are initialized, we send out a message to every other cluster member, telling them to run the `NewMember` hook. However, if those cluster members are also in the process of initializing, then this will fail and our cluster member won't initialize properly.
This allows `POST` and `GET` on `/cluster` to be available pre-init. In the case of `POST`, which is used for the above example, we will allow the request to go through it it's a cluster notification to run the hook. Otherwise, both methods will fail if the daemon has not been initialized, as before.

Allow NewMember hook before initialialization

---

internal/trust/remotes.go

Not sure how or why the certificate is nil yet, but at least this will cause the heartbeat to fail nicely and try again, rather than panic.

internal/trust/remotes: Check for empty remote certificate

---

internal/daemon/daemon.go

This lets us know which machine we are on when handling a request on the temporary listener specified by microcluster.Args.ListenPort

internal/daemon/daemon: Assign hostname as default name

---

microcluster/app.go

Allows for using `RemoteClient` without any TLS bits prior to bootstrap when we don't yet have a cluster cert.

microcluster/app: Http client for uninitialized systems

---

config/hooks.go
example/cmd/microd/main.go
internal/daemon/daemon.go

Replaces the `OnJoin` hook with two new hooks: `PreJoin` and `PostJoin`, which run before and after `OnNewMember` runs on every peer.

Split join hooks into Pre/Post

---

config/hooks.go

I tried to improve description of `PreJoin`, `PostJoin` and `OnNewMember` hooks, and their order/timings, based on the [comment](https://github.com/canonical/microcluster/issues/60#issuecomment-1544277206) by @masnax

Improve description of lifecycle hooks.

---

microcluster/app.go

Updates one more usage of LXD's logger. Weird go caching issue somehow made me able to build even with this function incorrect.

microcluster/app: Update call to lxd's logger

---

internal/trust/remotes.go
internal/trust/truststore.go

We use Load to set up the truststore the first time, so don't fail if it's empty on an uninitialized system.
Quickly going to merge this as `microcluster` is very broken atm :)

internal/trust/truststore: Don't fail on Load if truststore is empty

---

internal/db/update/update.go

Fixes an issue where schema updates would apply out of order due to the non-deterministic iteration of maps in `go`.

internal/db/update/update: Convert extended schema to sorted list

---

microcluster/app.go

When use ralative directory say ./a, it will not work.
This patch fixed the issue.

Fixed ralative state directory not work

---

config/hooks.go
example/cmd/microctl/main_init.go
example/cmd/microd/main.go
internal/daemon/daemon.go
internal/rest/resources/control.go
internal/rest/types/control.go
internal/state/state.go
microcluster/app.go

This PR adds an argument to `(*Microcluster).NewCluster` of the form `map[string]string` which is passed into the `OnBootstrap` hook. This allows clients to pass additional configuration that might be required at bootstrap.

Allow passing additional configuration during bootstrap

---

internal/endpoints/network.go
internal/endpoints/socket.go

Fixes a misleading error log because we were closing the listeners but not closing their contexts.

Cancel the listener context before closing it

---

config/hooks.go
example/cmd/microd/main.go
internal/daemon/daemon.go
internal/rest/client/cluster.go
internal/rest/resources/cluster.go
internal/state/state.go

The deletion API does actually support a `force` flag already, but I noticed that the `PreRemove` hook was actually explicitly blocked when `force=1` was set as a query parameter. This should definitely not be the behaviour, so I went ahead and just propagated the `force` param to each of `PreRemove` (which runs on the to-be-removed node) and `PostRemove`  (which runs on every other node after the node is removed). The `PreRemove` hook will now always fire, even if `force=1`.

Pass `force` to the Pre/PostRemove hooks

---

internal/rest/resources/cluster.go

FIX #79 
In the case the cluster is composed of 2 members, and you try to remove the voter. The code successfully transfers leadership to the spare member, but since cluster info is not updated, subsequent checks fail with "Found no voters to transfer leadership to".

internal/rest/resources: Refresh cluster info when assigning a role to another node

---

internal/daemon/daemon.go
internal/db/db.go
internal/db/dqlite.go
internal/db/update/global.go
internal/db/update/update.go
internal/rest/resources/control.go

Refactor the `internal/db/update` package such that it does not carry any implicit global state for the database migrations.
When trying to instantiate more than one microcluster instance, the global `updates` state would perform duplicate migrations on instances other than the first and thus fail.
- Create a `update.SchemaUpdateManager` type with the `Schema()`, `AppendSchema()`, `SchemaDotGo()` methods.
- Create a `globalSchemaUpdateManager` object
- Preserve the old `update.Schema()`, `update.AppendSchema()`, `update.SchemaDotGo()` functions, so that we don't break API. These use the global object, being backwards compatible.
- Update the microcluster instance creation to not use the global schema, but create its own schema instance and use that for initialization.
In …

internal/db/update: Drop implicit global state

---

.github/dependabot.yml
.github/workflows/commits.yml
.github/workflows/tests.yml
example/cmd/microctl/extended_cmd.go
example/cmd/microctl/sql.go
internal/db/dqlite.go

@masnax I made the needed changes to please golangci-lint but revive was too much so I made the `check-static` warn instead of hard failing for now.
I looked at building it but it wants `lxd-generate` and I couldn't quickly find where to pull it from. Something for a future PR :)

Add minimal CI tests

---

cluster/token_records.go

When using `ListJoinTokens()` the tokens do not match the join token that was given by `NewJoinToken()`, as it does not include the token name in the encoded string.
Note that this does not affect joining nodes, as either of the tokens works (the `name` field of the token is not used).

include name in encoded token when using `ListJoinTokens()`

---

internal/daemon/daemon.go
internal/rest/resources/shutdown.go
internal/state/state.go
microcluster/app.go

Simplifies the daemon's blocking action in response to #93 by @neoaggelos and a closer look at the `Daemon` and `App`.
This moves the blocking loop from `app.Start` into `daemon.Run` (previously `daemon.Init`) so that we no longer have to export the related context fields. Eventually they can be removed, but this prevents us from committing to them further in any solution to the bug that #93 addresses.
Additionally, `app.Start` now handles signals with `signal.NotifyContext`, which lets us treat all triggers of the daemon stop sequence in the same way, with one context. 
Any context passed to `app.Start` will be wrapped in a `signal.NotifyContext`, and the resulting child context will be used in `daemon.Run` to block on until it cancels from a signal or some other source outside the scope …

Use one context for cancelling the daemon

---

example/cmd/microd/main.go
internal/db/update/schema.go
microcluster/app.go

I fixed these while trying to run the tests... before I discovered that there are none. Didn't want to waste the work.
Fixes golangci-lint `SA1019`
EDIT: This should probably wait to be merged until after #99, as the deprecation occurred at in go 1.20.

Fix golangci lint

---

example/cmd/microctl/cluster_members.go
example/cmd/microctl/extended_cmd.go
example/cmd/microctl/main_init.go
example/cmd/microctl/shutdown.go
example/cmd/microctl/sql.go
example/cmd/microctl/tokens.go
example/cmd/microctl/waitready.go
example/cmd/microd/main.go
internal/rest/client/control.go
microcluster/app.go

- Remove context from `*microcluster.MicroCluster` struct
- Pass context during `(*MicroCluster).Start`, not during creation
- Update all `(*MicroCluster)` methods to accept a context and use that instead
- Update `microctl` for new API, use `cmd.Context()` instead of `context.Background()`
- Update `microd` for new API, use `cmd.Context()` instead of `context.Background()`

Specify context in all microcluster methods

---

internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/trust/remotes.go

* Makes the cluster join token error more descriptive to help debug join errors.
* Suppresses truststore initialization error, as we won't have any entries when the daemon first starts.

Clearer errors and logs

---

cluster/token_records.go
internal/rest/resources/tokens.go
internal/rest/types/tokens.go

Resolves the titular concern in #96 
@masnax I had mentioned that this caused cluster join to fail and... I can't reproduce it. Cluster forms up nicely. Likely had a messy worktree at the end of the day or some such. This passes what tests there are in #110.

Remove name from join token

---

client/client.go
example/api/extended.go
internal/daemon/daemon.go
internal/rest/client/client.go
internal/rest/client/truststore.go
internal/rest/resources/certificates.go
internal/rest/resources/cluster.go
internal/rest/resources/heartbeat.go
internal/rest/resources/resources.go
internal/rest/resources/truststore.go
internal/state/state.go
internal/trust/remotes.go

This PR cleans up some of the patchwork in the join API.
* Adds an entry to the truststore of each node in the cluster. Accepts a `types.ClusterMemberLocal` which is usually used to convert to a `trust.Remote` type for the truststore.
* Replaces the truststore with the given entry excluded on each node of the cluster. Also accepts a `types.ClusterMemberLocal`.
* Current behaviour 
* Only the dqlite leader, and whichever node forwarded the request to the dqlite leader trust a joining node as it goes through the join process. The rest of the cluster is only updated 30 seconds later on the next heartbeat. 
* New behaviour
* Just the dqlite leader will trust the joining node until it completes the join process. Finally, the joining node will inform the leader that it is done, at which point …

Add truststore API

---

internal/rest/resources/api_1.0.go

Untrusted systems should still be able to view this non-sensitive information. (name, address, database status, and soon likely API extensions).

Allow unauthenticated connections to /cluster/1.0

---

internal/daemon/daemon.go
internal/db/dqlite.go

Couple things:
* The truststore API was being used to update the cluster member's local node records each time their databases start, but this was causing a quorum loss loop because if the daemon restarts, no node will be available to handle the request and the database will close prematurely.
* Additionally slightly related is that when we close the dqlite connection, we first try to shut down the database, but if other nodes have already closed their dqlite connections then we won't be able to close the database and the defunct connection will be left open, causing problems if the daemon restarts too quickly. I've changed this to skip the error check for `db.Close` since `dqlite.Close` will close it for us. This is the same behaviour as in LXD today.

Fix bug introduced with truststore API

---

cluster/cluster_members.go
cluster/cluster_members.mapper.go
example/api/extensions.go
example/cmd/microd/main.go
internal/daemon/daemon.go
internal/db/db.go
internal/db/db_test.go
internal/db/dqlite.go
internal/db/update/update.go
internal/db/update/update_test.go
internal/extensions/extensions.go
internal/extensions/extensions_test.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/types/cluster.go
internal/state/state.go
microcluster/app.go

Introducing an 'extensions' endpoint in MicroCluster would help in scenarios where service A (backed by MicroCluster) needs to check that service B (also backed by MicroCluster) has a certain feature (e.g, does the installed version of MicroOVN supports custom encapsulation ip that has been entered by a user in a MicroCloud setup)
Required by https://github.com/canonical/microovn/pull/121 and https://github.com/canonical/microovn/pull/113 and https://github.com/canonical/microcloud/pull/245

Add a new 'runtime extension' system to MicroCluster

---

internal/rest/resources/cluster.go

The PreRemove hook was intended to be used before the node was removed from the database, however it seems it was incorrectly only being run before the node was removed from dqlite.
This poses some issues because an application using microcluster may want to clean up entities associated to records in the database for a particular node, but by removing the node from the database first, `ON DELETE CASCADE` will clear all of that state.

Run PreRemove hook before modifying the database

---

internal/extensions/extensions.go
internal/extensions/extensions_test.go

The previous regex was failing on `custom_extension_a_0` which is used in the example package.

Fix api extension regex

---

example/cmd/microd/main.go
internal/db/db.go

Cleans up a noisy log and fixes the example package, which was failing to run the `OnStart` hook because of an incorrectly ordered set of external API extensions.

Misc fixes

---

internal/daemon/daemon.go
internal/rest/client/hooks.go
internal/rest/resources/cluster.go
internal/rest/resources/hooks.go
internal/rest/resources/hooks_test.go
internal/rest/resources/resources.go
internal/rest/types/hooks.go

Closes #109 
Depends on #113 
* Adds an endpoint to execute multi-node hooks on a particular cluster member. The hook type is specified by a `types.HookType` integer, and the arguments of the hook are passed in with the `types.HookNewMemberOptions` struct and the `types.HookRemoveMemberOptions` struct. This replaces the current implementation which relies on cluster notifications, which is confusing and bloats the cluster management API.
* The only multi-node hooks are currently `OnNewMember`, `PreRemove`, and `PostRemove`, so only these are supported by the API at this time. The other hooks are local to a particular node and so do not need to be run by a different node over the network.
* The cluster management network requires the database, and so the database must be open for the API …

Add hooks API

---

internal/db/update/schema.go

We can't be sure which tables specified by external users of microcluster reference internal tables. So just broadly turn off foreign keys while applying internal schema updates, and turn it back on afterward.

Disable foreign keys for internal updates

---

internal/daemon/daemon.go
internal/rest/resources/resources.go
internal/rest/rest.go
microcluster/app.go
rest/access/handlers.go
rest/rest.go

Allows microcluster downstreams to specify extra servers that they would like microcluster to set up. Handlers in the extension servers will have access to microcluster state.
To do:

Allow running extra network listeners

---

internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/types/tokens.go

Reverts the joiner and cluster if there is an error during the join process.
* Instead of iterating over every join address to find which system initially consumed our join token, the address of this system is now included in the response returned by validating the join token.
* Allows reducing a 2 system cluster to a 1 system cluster, as there is no issue with quorum since the roles are turned over first.
* If deleting a node with `?force=true`, then errors related to reaching the node will be ignored as we are forcibly removing it and it may be unreachable.
* If the joiner fails to join the cluster, a revert block is executed which resets the state of the joiner back to pre-initialization, and additionally attempts to send a request to the existing cluster to clear out any remaining …

Recover from join failures

---

example/test/main.sh
internal/daemon/daemon.go
internal/sys/os.go

I'm having a hard time coming up with any situation where it's safe to start the daemon if a control socket still exists in the state dir.
I'm doing this check anyway as a part of cluster recovery.

internal: Prevent Daemon startup if control socket is present

---

internal/daemon/daemon.go

If the upgrade notification fails, that does not mean that we have to stop starting the local node, rather it is informing us of an issue on a remote cluster member, so we can ignore it during set up.

internal/daemon: Don't error out if upgrade notification fails

---

client/client.go
example/client/client.go
internal/daemon/daemon.go
internal/db/dqlite.go
internal/rest/client/client.go
internal/rest/client/cluster.go
internal/rest/client/control.go
internal/rest/client/heartbeat.go
internal/rest/client/hooks.go
internal/rest/client/ready.go
internal/rest/client/shutdown.go
internal/rest/client/sql.go
internal/rest/client/tokens.go
internal/rest/client/truststore.go
internal/rest/resources/resources.go
internal/rest/types/server.go
microcluster/app.go
rest/rest.go
rest/types/endpoint.go

The hardcoded `1.0` value for resources supplied by the project using microcluster will be removed by #142, which means we need a way to supply the endpoint prefix to client functions.
This PR moves the type definition for `EndpointType` into the API types package, and moves all internal implementations into the internal API types package. It is also renamed to `EndpointPrefix` for clarity.
Then, when #142 is merged, this value will be specified in the set of `Resources` supplied to microcluster, and can be passed into the `Query` method.

Move EndpointType to `types` package.

---

internal/rest/resources/cluster.go
internal/rest/resources/control.go

#106 validated that cluster member names must be a hostname. I don't see any reason not to also allow FQDN cluster member names. Currently, at least Sunbeam has been using FQDNs as cluster member names.

Allow FQDN cluster member names

---

.github/.jira_sync_config.yaml

`.jira_sync_config.yaml` is a configuration file to allow the creation of Jira issues when a particular tag (`Jira`) is assigned to the GitHub issue. It uses [gh-jira-sync-bot](https://github.com/canonical/gh-jira-sync-bot). The issues in Jira are grouped in a specific epic defined in the config file, but the parent epic can be changed without affecting the synchronization. The default issue type assigned in Jira is "Bug" but it can be changed assigning a different label (`feature`,`improvement`, `investigation`) to the GitHub issue.

github: added .jira_sync_config.yaml for the synchronization with Jira

---

cluster/cluster_members.go
internal/daemon/daemon.go
internal/db/db.go
internal/db/dqlite.go
internal/db/update/schema.go
internal/db/update/update.go
internal/rest/resources/api_1.0.go
internal/rest/resources/certificates.go
internal/rest/resources/control.go
internal/rest/resources/heartbeat.go
internal/rest/resources/shutdown.go
internal/rest/rest.go

Closes #66
Rather than just returning `Daemon not yet initialized` when the database is offline, there are now more nuanced errors:
* `Database is not yet initialized` will be reported if the database is offline (prior to starting dqlite, or when the database is stopped)
* `Database is still starting` will be reported after dqlite has begun starting up, but before it has finished.
* `Database upgrade is in progress: %d cluster members have not yet received the update` will be reported for as long as a system is blocking, waiting for a schema upgrade or API extension to be committed. 
The number returned by the latter error will be fetched from the cluster members table as a count of all systems whose schema versions are smaller than the local schema version. Additionally, `sqlite_master` …

Add descriptive errors for database status checks

---

example/cmd/microctl/cluster_members.go
internal/rest/resources/cluster.go
internal/rest/types/cluster.go

Adds `MemberUpgrading` and `MemberNeedsUpgrade` to the list of possible cluster member statuses.
Consequentially, this means we need to set `AllowedBeforeInit=true` to the `/cluster` API. In the POST case, we still enforce that the database must be fully ready. 
But for listing cluster members, as long as the cluster is at least in a waiting state, we can try to grab the current list of members. In such a case, we will compare those cluster members' schema versions to our own local version, and set `UPGRADING` as the status if they match our's, or `NEEDS UPGRADE` if they do not.

Add upgrade progress to cluster member status.

---

internal/daemon/daemon.go
internal/db/db.go
internal/db/dqlite.go

If the daemon crashed or stopped uncleanly due to an error, then the control socket file might still be present in the state directory. This means the daemon will enter a restart loop until the control socket is manually removed.
Instead, we can just attempt to re-connect to the control socket. If it's already in use then that will error out the daemon anyway.

internal/daemon: Attempt to re-use control.socket if present

---

example/api/servers.go
example/cmd/microd/main.go
internal/daemon/daemon.go
internal/rest/resources/resources.go
microcluster/app.go
rest/rest.go

This changes the structure of the extension servers a bit to make them play more nicely with the core API.
* Removes `CoreAPI` flag, instead any `Server` without an address/certificate will be set up with the core listener. 
* Adds `PreInit` flag. This signifies whether the `Server` should start prior to initialization if `ListenPort` is defined on the daemon.
* Adds 2 functions: `addCoreServers` and `addExtensionServers`. The former captures all entries in the `Servers` list that either do not have an address & certificate, or whose fields match the core values, and offers all of their resources over the same server. The latter starts up a new server for any remaining `Server`s whose address is defined.
* Adds a helper `AddServers` for applying the extension server config to …

Streamline extension servers with core API

---

internal/rest/client/client.go

Recently we merged #142 which allows the user to define their own path prefix for a client query. However, if the prefix is `""`, then we may end up with a path like `//some-path` in [QueryStruct](https://github.com/canonical/microcluster/blob/db6075a4cf00db01687e26e61a08fe679a6f567b/internal/rest/client/client.go#L275). This PR should resolve the issue.

Client: remove "/" from path prefix if `endpointType` has empty value

---

internal/rest/rest.go
rest/access/handlers.go
rest/rest.go

- Allow `AccessHandler` to return a callback that can modify the `http.ResponseWriter` object.
- In an upstream project, endpoints authentication applied by using the custom `AccessHandler` may need to write to the response regardless of success or failure. Currently in microcluster if an `AccessHandler` returns `EmptySyncResponse`, then we will not be able to access the response object even if we need to write to it.
- The upstream project can get around this issue by writing auth data to the request context and handle it in the actual endpoint handler. However, this approach tend to require the authentication logic to be split up which makes the code difficult to understand.

allow modification of response if access handler returns a callback

---

cluster/recover.go
example/cmd/microctl/cluster_members.go
example/test/main.sh
internal/daemon/daemon.go
internal/recover/recover.go
microcluster/app.go

A few things:
- Updated [the spec](https://discourse.ubuntu.com/t/microcluster-microcloud-quorum-recovery/45560) to reflect what I've implemented here
- This works with microd; ~~tests in the works~~ see below.
- I've not implemented address changes as it requires an update to the database once it's up; @masnax mentioned that patches in LXD were relevant. I'll throw the code I do have pursuant to address changes in a branch soon.
- ~~Also still working on the `TODO` to reach out to the rest of the cluster~~
- Setting all the node roles except one voter to `stand-by` causes dqlite to fail; I'd like to find out why but it's not a high priority as the other configurations I've tried (including stand-by members) work. +1 on a fix for #66 .
~~This PR depends on #146~~ Merged
LXD-1118

Minimal cluster recovery

---

internal/db/dqlite.go

`go-dqlite` sets a context on calls to the `DialFunc` specified by us that may have already been cancelled. In such cases we shouldn't need to continue to execute `Dial`, so this passes the context down to `dial.DialContext`.

internal/db: Pass dial context through to dialer.Dial

---

Makefile

Even Go 1.21 has improved support for it since 1.21.11 (https://github.com/golang/go/issues/62278)

Makefile: the toolchain directive should be better supported now

---

internal/extensions/extensions.go
internal/rest/resources/api_1.0.go
internal/rest/types/server.go

needed by: https://github.com/canonical/microcloud/pull/245/commits/e6eadc1981614ae9d1a909239243dde93a901841
___
This way, a MicroCluster app started in an particular snap application (like `microovn`), when its recovered as a MicroCluster app in `microcloud`, can expose its API extensions.

microcluster: Add the apiExtensions to the MicroCluster app args

---

config/hooks.go
example/api/servers.go
example/cmd/microd/main.go
internal/config/daemon.go
internal/daemon/daemon.go
internal/endpoints/endpoint.go
internal/endpoints/endpoints.go
internal/endpoints/network.go
internal/rest/client/cluster.go
internal/rest/client/daemon.go
internal/rest/client/hooks.go
internal/rest/resources/certificates.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/resources/daemon.go
internal/rest/resources/hooks.go
internal/rest/resources/resources.go
internal/rest/types/hooks.go
internal/rest/types/tokens.go
internal/state/state.go
internal/sys/os.go
microcluster/app.go
rest/access/handlers.go
rest/rest.go
rest/types/certificate.go
rest/types/config.go
rest/types/server.go

This PR adds missing features to the additional network listeners feature:
1. **Add additional servers by name**
This allows referencing them later when updating their configuration and loading the server certificates
2. **API for setting arbitrary certificates**
You can now set arbitrary certificates (besides the `cluster` certificate) which allows downstream projects to provide custom certificates. They are distributed across active cluster members and shared between new members joining the cluster .
3. **API to modify additional network listeners**
The local daemon's config got moved into its own type which allows easy access to downstream components. This is used to allow updating the non-immutable fields of additional network listeners.
4. **Local daemon's config update hook**
As …

Extend additional network listener concept

---

internal/rest/resources/api_1.0.go
rest/types/addrport.go

This API endpoint should be available at all times to query the daemons' state information. However, if it is not yet initialized, its address may not be set if the project is not using `PreInitListenAddress`. 
In these cases, there is technically no address yet so we can just return an empty `types.AddrPort` instead.
Calling `String()` on this type would return `invalid AddrPort` which I found to be a bit unintuitive so instead the wrapper type has been given its own `String` method which returns an empty string if the AddrPort is empty, and otherwise falls back to the internal `String` implementation.

Allow empty address for `GET /cluster/1.0`

---

example/api/extended.go
example/cmd/microd/main.go
internal/daemon/daemon.go
internal/rest/resources/api_1.0.go
internal/rest/resources/certificates.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/resources/daemon.go
internal/rest/resources/database.go
internal/rest/resources/heartbeat.go
internal/rest/resources/hooks.go
internal/rest/resources/hooks_test.go
internal/rest/resources/ready.go
internal/rest/resources/shutdown.go
internal/rest/resources/sql.go
internal/rest/resources/tokens.go
internal/rest/resources/truststore.go
internal/rest/rest.go
internal/state/hooks.go
internal/state/state.go
microcluster/app.go
rest/access/handlers.go
rest/rest.go
state/state.go

Closes #133 
* Replaces `state.State` with a new `state.InternalState` struct which implements a `state.State` interface. This means that the fields of `State` are not overwrite-able by the upstream project, and internal functions are not exposed externally.
* To avoid import cycles, `config.Hooks` is moved into the `state` package as well. This is actually not too bad since the `config` package was a confusing place for it. It also means we don't need to define functions and can just provide the whole type to `InternalState`

Use an interface for `State`

---

example/Makefile
example/cmd/microctl/main.go
example/cmd/microd/main.go
example/version/version.go
internal/daemon/daemon.go
internal/rest/resources/api_1.0.go
internal/rest/types/server.go
internal/state/state.go
microcluster/app.go

Take a (required) project version via the microcluster app args and include it in the response from `GET /cluster/1.0`. This will allow MicroCloud to enforce version requirements on its sub-snaps.
This also adds a build-time constant version (`git describe`) to the example.
LXD-1279

Project version

---

internal/db/db.go
internal/db/db_test.go
internal/db/update/schema.go

This is modelled after the same feature in LXD:
https://github.com/canonical/lxd/blob/34a108012a4b47c045503c9651a37091ddb8bacb/lxd/db/schema/schema.go#L122
This provides a way for an administrator to execute sql during database startup before any schema updates are applied.
It also allows us to queue up changes to the global DB before it has been started (useful during recovery).
LXD-1316

internal/db: Load `StateDir/patch.global.sql` during schema Ensure

---

internal/rest/resources/control.go

Fixes an issue where the join process would fail if a node in the join_address list is unreachable.
When a token is created, it includes the IP addresses of all nodes in the cluster. If a node is removed between the token creation and joining, the join process previously failed because it tried to connect to the non-existent node.
Now, the client discovery logic will continue attempting to connect to other nodes in the join_address list instead of failing early. This ensures that the join process can succeed as long as at least one node is reachable.

internal/rest/resources: Improve join logic to handle unreachable nodes

---

example/cmd/microd/main.go
internal/daemon/daemon.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/resources/heartbeat.go
internal/rest/resources/hooks.go
internal/rest/resources/hooks_test.go
internal/state/hooks.go
internal/state/state.go

Since we are no longer exposing `state.Context`, we need to pass a context as argument to each hook to manage its lifetime.
For most hooks, this means their parent context is the request context for the API that triggered the hook. The actual context passed to the hook will be cancelled immediately after the hook returns. This is to discourage long-lived goroutines running in these hooks.
The exception is `OnStart`. For `OnStart`, which is intended to start services that work with microcluster, the lifetime should be equivalent to the daemon itself. So the shutdown context of the daemon is supplied to this hook. Its comment has been updated to reference this.

Manage hook lifecycles with context

---

example/cmd/microctl/cluster_members.go
go.mod
internal/recover/recover.go
internal/trust/remotes.go

In the code we are using different versions (v2 and v3) of the yaml dependency.
This should fix future automatic PRs like https://github.com/canonical/microcluster/pull/183 as `v3` was also listed as indirect dependency.
Fixes https://github.com/canonical/microcluster/pull/183.

Go: Consistently use `gopkg.in/yaml.v3`

---

microcluster/app.go

Make sure all non self-explanatory parameters of the microcluster `Start()` func are documented properly.

Doc: Clarify `apiExtensions` parameter

---

internal/daemon/daemon_test.go

This PR is a follow up on https://github.com/canonical/microcluster/pull/174 and adds checks for the configuration/update of the extension servers.

internal/daemon: Add UpdateServers tests

---

example/cmd/microctl/cluster_members.go
example/test/main.sh
internal/db/db.go
internal/recover/recover.go
microcluster/app.go

Allows address changes during cluster recovery.
The PR:
- Moves the rest of the recovery code into `internal/recover` instead of being awkwardly split between `microcluster/app.go` and the recover package
- Adds address updates for:
- `daemon.yaml`
- The trust store
- `database/info.yaml`
- `database/cluster.yaml`
- The global database (via `patch.global.sql`)
I'm not a massive fan of  rewriting both `info.yaml` and `cluster.yaml` (owned by go-dqlite) but `dqlite.App` won't start otherwise (see 741e6939a3b0927fa87717f72628198092191707 for details). We also need to update `info.yaml` on every member, so I can't PR against go-dqlite unless we move most of the recovery tarball handling too.
@masnax Not sure what your review process looks like but my feeling is Tom would prefer smaller …

Address changes

---

internal/rest/resources/control.go

We already do this cleanup when a node fails to join the cluster, but we should also try to reset the daemon if bootstrapping fails, so that the node can be easily re-initialized.

internal/rest/resources: Reset the daemon if bootstrapping fails

---

internal/rest/resources/control.go

This allows accessing the database from within the hook before
closing the database and re-executing the daemon.

Bootstrap: Run the PreRemove hook before re-exec

---

internal/rest/resources/control.go

Execute the PreRemove hook on the node that tried to join. This aligns a failed join with the behavior of a failed bootstrap. With that, PreRemove can generally be used to add custom cleanup logic.

Join: Run the PreRemove hook on join failures

---

internal/db/dqlite.go
internal/rest/client/client.go
internal/rest/client/cluster.go
internal/rest/client/daemon.go
internal/rest/client/heartbeat.go
internal/rest/client/sql.go
internal/rest/client/tokens.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/rest/resources/heartbeat.go
internal/rest/resources/resources.go
internal/rest/types/server.go
microcluster/app.go

This PR ensures that all the API endpoints which are used by public facing client functions are also listed under the `/core/1.0` path instead of `/core/internal`.
In addition the PR does the actual rename of `/cluster/(1.0|internal)` to `/core/(1.0|internal)` as https://github.com/canonical/microcluster/pull/137 looks to have modified unused constants. Looks we somehow had duplicate constants in the code base.
I have also moved the public facing `types.ExtendedEndpoint` that represents the `/1.0` prefix into the top level `/rest/types` package.

Harmonize public facing endpoints

---

internal/rest/client/tokens.go
internal/rest/resources/resources.go

This makes it so that simply trusting the cluster is not enough to issue a join token, it has to be issued from an actual cluster member.

internal/rest/resources: Don't allow token issuing over the network

---

cluster/token_records.go
cluster/token_records.mapper.go
example/cmd/microctl/tokens.go
internal/db/update/update.go
internal/rest/client/tokens.go
internal/rest/resources/tokens.go
internal/rest/types/tokens.go
microcluster/app.go

CC @MggMuggins @boltmark 
This adds the necessary schema/client/api type changes necessary for join token expiration, following a similar pattern to LXD's expiration date handling. 
As of now, the field is unused when specified to the API, so the remaining steps would be:
* On `POST` to `/core/internal/tokens`, if `req.ExpireAfter` is non-zero, set the expiration of the token to that duration after the current time, when adding the token record to the database.
* On each heartbeat handled by the leader, check all token expirations and delete any expired ones. There's lots of transactions here that can be re-used.
* Update example CLI to take a flag for setting the expiration, this can default to 3 hours like LXD's join tokens.
* Update example CLI to show the expiration date when listing …

Add expiry date column to `core_token_records`

---

Makefile
go.mod
go.sum
internal/daemon/daemon.go
internal/db/dqlite.go
internal/rest/resources/cluster.go
internal/rest/resources/control.go
internal/sys/os.go
rest/types/certificate.go

Closes #96 
The LXD dependency was updated as well to be able to set the SAN name of the `server.crt` certificate to something other than the hostname.
Since the `server.crt` is generated when the daemon first starts, it will first be populated with the system hostname. However, during the `init` sequence the daemon name can be set to any valid FQDN, so we have to replace the `server.crt` before it's sent to the cluster to request authorization to join the cluster.
To be able to replace `server.crt`, `ReloadCert` has been updated to accept `server` as a valid certificate to replace as long as the dqlite database has not yet been initialized. 
Finally, when we send the certificate to the dqlite leader, it verifies that the SAN matches the name used when the join token was first issued.

Verify server.crt on cluster join request

---

cluster/token_records.go
example/cmd/microctl/tokens.go
example/test/main.sh
internal/rest/resources/cluster.go
internal/rest/resources/heartbeat.go
internal/rest/resources/tokens.go

Fixes #199.
I got sick of feeling like I couldn't test effectively with the system tests, so this includes a refactor to separate them out a bit. Should make reviewing changes easier in future. They're far from perfect but still better than they were. I can split them into a different PR if that would be preferred.
Regarding tokens:
- Don't return an expired token from `GET tokens/`
- Insert an expiry date if one is provided during token creation
- Delete expired tokens on heartbeat
- Token support in `microctl`
LXD-1349

Join token expiration
